name: Daily News Push

on:
  schedule:
    - cron: '0 0 * * *'  # 每日 UTC+0 → 台灣時間早上 08:00 執行
  workflow_dispatch:

jobs:
  push-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run push script
        env:
          WORKER_URL: https://line-news-pusher.stonersheart.workers.dev
        run: node fetch-news.js
